version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1232478847
      POSTGRES_DB: emma
      
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - "5432:5432"
