databases:
  - name: emma
    plan: free
    databaseName: emma
    user: emma

services:
  - type: web
    plan: free
    name: newspaper
    runtime: python
    buildCommand: "./build.sh"

    startCommand: "uvicorn newspaper.asgi:application --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: emma
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4