# Generated by Django 5.0.4 on 2024-09-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_alter_message_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(max_length=500, upload_to='posts_images/'),
        ),
    ]
