# Generated by Django 5.0.4 on 2024-09-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0042_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
    ]
