# Generated by Django 5.0.4 on 2024-09-05 22:41

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0043_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=85, scale=None, size=[900, 630], upload_to='post_images/'),
        ),
    ]
